// This file is the Vercel serverless function entry point.
// It imports the pre-compiled bundle generated by `pnpm build:api`.
// Do NOT edit this file; edit api/index.ts instead.
export { default } from "./_server.js";
